### ISSUE TITLE
Hello, I want to bring to your notice that the article on the medium of 500x performance also has 1 issue stated

### ISSUE THREAD

**Issue by kingx619** [shabeer-ali-m/php-super-cache#1]
The link is here
https://medium.com/@kerry.schwab/this-approach-has-a-couple-of-issues-youll-want-to-fix-9571546fd026

can you implement this approch in your superchache file ??

**Comment by shabeer-ali-m** [comment]
@kingx619 Sure will look into it.

**Comment by kingx619** [comment]
Thanks for the prompt reply...:D This issue was mentioned inside the comments inside the article on medium..:D
